version: '3.8'

services:
  api-gateway:
    image: api-gateway:latest
    ports:
      - "8086:8086"
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
    networks:
      - environment-pollution-network

networks:
  environment-pollution-network:
    external: true
    name: project_environment-pollution-network
